INSERT INTO orders (
      awb,
      fullName_sender,
      contactPerson_sender,
      phone_sender,
      email_sender,
      county_sender,
      city_sender,
      address_sender,
      fullName_receiver,
      contactPerson_receiver,
      phone_receiver,
      county_receiver,
      city_receiver,
      address_receiver,
      nrEnvelope,
      nrParcel,
      weight,
      length,
      width,
      height,
      date,
      hour,
      preference1,
      preference2,
      preference3,
      payment,
      mentions,
      status
    )
  VALUES (
      1234,
      'Viziteu David Andrei',
      'Viziteu Davd Andrei',
      '0712345678',
      'viziteu.david@gmail.com',
      'Iași',
      'Iași',
      'Izvor 14',
      'fullName_receiver',
      'contactPerson_receiver',
      'phone_receiver',
      'Ilfov',
      'București',
      'address_receiver',
      'nrEnvelope',
      'nrParcel',
      'weight',
      'length',
      'width',
      'height',
      'date:date (pickup date)',
      'hour:time (pickup time)',
      'preference1:varchar',
      'preference2:varchar',
      'preference3:varchar',
      'payment:varchar',
      'mentions:varchar',
      'status:varchar'
    );