GET http://localhost:8000/api/private/driver-task?county=Iași

###

GET https://example.com/topics/1 

###

POST https://example.com/comments 
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}